#!/bin/bash
## Report the parameters of the current configuration

## Report the SDC path and CLK_PERIOD
echo "SDC: $SDC_FILE"
echo "CLK_PERIOD: $CLK_PERIOD"
echo "ABC_CLOCK_PERIOD_IN_PS: $ABC_CLOCK_PERIOD_IN_PS"
echo "CORE_UTILIZATION: $CORE_UTILIZATION"
echo "CORE_ASPECT_RATIO: $CORE_ASPECT_RATIO"

## Report LB_ADDON
echo "PLACE_DENSITY_LB_ADDON: $PLACE_DENSITY_LB_ADDON"
## Report CELL_PAD_IN_SITES_GLOBAL_PLACEMENT
echo "CELL_PAD_IN_SITES_GLOBAL_PLACEMENT: $CELL_PAD_IN_SITES_GLOBAL_PLACEMENT"
## Report CELL_PAD_IN_SITES_DETAIL_PLACEMENT
echo "CELL_PAD_IN_SITES_DETAIL_PLACEMENT: $CELL_PAD_IN_SITES_DETAIL_PLACEMENT"

## DPO
echo "ENABLE_DPO: $ENABLE_DPO"

## Report GPL_TIMING_DRIVEN
echo "GPL_TIMING_DRIVEN: $GPL_TIMING_DRIVEN"
## Report GPL_ROUTABILITY_DRIVEN
echo "GPL_ROUTABILITY_DRIVEN: $GPL_ROUTABILITY_DRIVEN"

## Report TNS_END_PERCENT
echo "TNS_END_PERCENT: $TNS_END_PERCENT"

## Report RECOVER_POWER
echo "RECOVER_POWER: $RECOVER_POWER"

## Report SYNTH_HIERARCHICAL
echo "SYNTH_HIERARCHICAL: $SYNTH_HIERARCHICAL"

## Report CTS_CLUSTER_SIZE
echo "CTS_CLUSTER_SIZE: $CTS_CLUSTER_SIZE"
## Report CTS_CLUSTER_DIAMETER
echo "CTS_CLUSTER_DIAMETER: $CTS_CLUSTER_DIAMETER"

## Report the FASTROUTE_TCL
echo "FASTROUTE_TCL: $FASTROUTE_TCL"

## Report PIN_LAYER_ADJUST
echo "PIN_LAYER_ADJUST: $PIN_LAYER_ADJUST"
## Report UP_LAYER_ADJUST
echo "UP_LAYER_ADJUST: $UP_LAYER_ADJUST"

## Report the job name
